#pragma once

#include <Arduino.h>

typedef enum {
    ERROR_INIT_FAILED,
    ERROR_TIMEOUT,
    ERROR_INVALID_STATE,
    ERROR_INVALID_COMMAND,
    ERROR_INVALID_ARGUMENT,
    ERROR_INVALID_RESPONSE,
    ERROR_TEST_FAILED,
    ERROR_NO_MEM,
    ERROR_INTERNAL,
    NO_ERROR = 99
} TesterError;